manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 8e065d55b916481ef06ce37cddedb84cf1d15d99 # main as of 2025-02-01, last known working bootloader
      import: app/west.yml
    - name: zmk-leader-key
      remote: urob
      revision: v0.3 # set to same as ZMK version above
    - name: zmk-helpers
      remote: urob
      revision: v0.3
  self:
    path: config
